### ISSUE TITLE
Hidden Fields visible on Registration page

### ISSUE THREAD

**Issue by timjrye** [A5hleyRich/BuddyPress-Admin-Only-Profile-Fields#2]
Hi,

Great plugin - works perfectly and does exactly what I need, except that hidden fields are still visible on the registration page. Is there any way I can hide the fields there too?

Thanks!

**Comment by A5hleyRich** [comment]
Hey,

To be honest I haven't looked if this is possible, so I'll take a look and let you know. Probably be the weekend though now.

Ashley

**Comment by timjrye** [comment]
Hi - did you manage to figure this out? I don't mean to bug you, but I'm waiting for your response before I make my site live. Thanks!

**Comment by A5hleyRich** [comment]
Hi,

Sorry for the delay in getting back to you. I've just looked into this and BuddyPress doesn't provide any means of filtering the registrations fields.

However, there are two ways around this:
1. Add the hidden fields to a separate group
2. Adjust your theme's register.php file to hide the fields

**Comment by timjrye** [comment]
Thanks for your help. I decided to simply hide the field with CSS by editing the theme's register.php file, in order to avoid any potential issues with the field being required for registration.
